### ISSUE TITLE
mobx_codegen should support Flutter's codegen integration

### ISSUE THREAD

**Issue by rrousselGit** [mobxjs/mobx.dart#185]
Since a few months ago, Flutter includes built-in support for code-generation tools through the `pubspec.yaml`.

This means that Flutter automatically runs the code-generator on `flutter build` and `flutter run`, and can be triggered manually using `flutter generate`.

See https://github.com/flutter/flutter/issues/27141 for more information.

For some reasons, trying to use `mobx_codegen` with this new method crashes:

```dart
Deserializing '[ServerLog, level, INFO, message, About to build [mobx_provider]...]' to 'unspecified' failed due to: Tried to construct class "ServerLog" with null field "log". This is forbidden; to allow it, mark "log" with @nullable.
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:125:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:104:18)
#2      new BuildDaemonClient._.<anonymous closure> (package:build_daemon/client.dart:83:36)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#9      _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#17     _StreamController._add (dart:async/stream_controller.dart:640:7)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#24     _StreamController._add (dart:async/stream_controller.dart:640:7)
#25     _StreamController.add (dart:async/stream_controller.dart:586:5)
#26     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1138:21)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#34     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#35     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#43     _StreamController._add (dart:async/stream_controller.dart:640:7)
#44     _StreamController.add (dart:async/stream_controller.dart:586:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#46     _rootRunUnary (dart:async/zone.dart:1136:13)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by rrousselGit** [comment]
This is likely caused by an incompatible version somewhere.

Although it's difficult to test since we can't test it on local packages... Only pub dependency works at the moment.

**Comment by pavanpodila** [comment]
Wow, this can drastically simplify the Developer Experience. Look forward to this becoming stable. @rrousselGit looks like you already on top of this 👍

**Comment by rrousselGit** [comment]
Ah, no. I'm on #139. I just happened to come across this issue

**Comment by pavanpodila** [comment]
Still its a good find. Looks very promising

**Comment by jonahwilliams** [comment]
I think this is actually an issue with flutter, try adding the following line to the pubspec:

```
builders:
   build_daemon: 0.6.1
```

This is fixed at master and won't be required shortly, but there is currently a small incompatibility that this works around.

**Comment by pavanpodila** [comment]
@jonahwilliams I am happy to wait a bit if it will be fixed shortly. Is "shortly" in days or weeks :-) ?

**Comment by jonahwilliams** [comment]
This is for users of the package, not the package author. "shortly" varies with how often users update flutter, so I can't say.

**Comment by pavanpodila** [comment]
Ah thanks for clarifying

**Comment by tomduncalf** [comment]
I suggest this issue should be closed as the codegen functionality is deprecated: https://github.com/flutter/flutter/issues/61508

**Comment by rrousselGit** [comment]
Agreed
