### ISSUE TITLE
Investigate test_coverage failures on CircleCI

### ISSUE THREAD

**Issue by shyndman** [mobxjs/mobx.dart#356]
This exception is frequent:
```
Unhandled exception:
Tests failed with exit code 255
#0      runTestsAndCollect (package:test_coverage/src/functions.dart:120:5)
<asynchronous suspension>
#1      main (file:///root/.pub-cache/hosted/pub.dartlang.org/test_coverage-0.4.0/bin/test_coverage.dart:51:9)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Reported to `test_coverage` package here: https://github.com/pulyaevskiy/test-coverage/issues/14

**Comment by pavanpodila** [comment]
This has been plaguing is for quite some time!

**Comment by shyndman** [comment]
Now that `test_coverage`'s stdout is being shown, it looks like this is the result of a test failing. Nice!

More details here: https://app.circleci.com/jobs/github/mobxjs/mobx.dart/2246
Stack:
```
package:mobx/src/core/context.dart': 
Failed assertion: line 197 pos 18: '_state.isWithinBatch': Changing observable 
values outside actions is not allowed. Please wrap the code in an "action" if this 
change is intended. Tried to modify Observable@30

  dart:core-patch/errors_patch.dart 42:39                       _AssertionError._doThrowNew
  dart:core-patch/errors_patch.dart 38:5                        _AssertionError._throwNew
  package:mobx/src/core/context.dart 197:18                     ReactiveContext.enforceWritePolicy.<fn>
  package:mobx/src/core/context.dart 202:6                      ReactiveContext.enforceWritePolicy
  package:mobx/src/core/observable.dart 51:14                   Observable.value=
  test/action_test.dart 291:7                                   main.<fn>
```

There is also a second class of error that occurs with `mobx_codegen`, as seen here:  https://app.circleci.com/jobs/github/mobxjs/mobx.dart/2245

Stack:
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0#0     
_ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:4411:7)

#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:731:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:16966:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:1825:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:196:42)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:140:43)
#8      List.forEach (dart:core-patch/growable_array.dart:285:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:140:18)
#10     new SummaryBasedDartSdk (package:analyzer/src/summary/summary_sdk.dart:32:18)
#11     analysisDriver (package:build_resolvers/src/analysis_driver.dart:26:13)
#12     AnalyzerResolvers._ensureInitialized.<anonymous closure> (package:build_resolvers/src/resolver.dart:189:20)
<asynchronous suspension>
#13     AnalyzerResolvers._ensureInitialized (package:build_resolvers/src/resolver.dart:192:6)
#14     AnalyzerResolvers.get (package:build_resolvers/src/resolver.dart:197:11)
#15     BuildStepImpl.resolver (package:build/src/builder/build_step_impl.dart:73:54)
#16     _Builder.build (package:source_gen/src/builder.dart:64:32)
#17     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#18     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#19     Future.wait (dart:async/future.dart:393:26)
#20     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
```

Reported here: https://github.com/dart-lang/build/issues/2589

**Comment by pavanpodila** [comment]
Closing this for now as we have moved to Github Actions where it seems to be quite reliable. #400
