### ISSUE TITLE
flutter_mobx exception does not print the stack trace in console

### ISSUE THREAD

**Issue by neokree** [mobxjs/mobx.dart#458]
As my comment in #337 the latest version does not show the stack trace in console. 

Versions used:
```
mobx: ^1.0.2+2
flutter_mobx: ^1.0.1
mobx_codegen: ^1.0.2
```

console error:
```
════════ Exception caught by flutter_mobx ══════════════════════════════════════════════════════════
The following MobXCaughtException was thrown:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")

════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
MobXCaughtException: NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")
The relevant error-causing widget was: 
  Observer file:///Users/neokree/Documents/Flutter/project/lib/src/ui/core/component/map/widget.dart:342:18
════════════════════════════════════════════════════════════════════════════════════════════════════
```

At this time to see the stack trace I need to debug the app and set a breakpoint on the `observer_widget_mixin.dart:89`, so I can get the exception that will be thrown and see the stacktrace.

**Comment by deadsoul44** [comment]
I can also confirm this behavior. Full stack trace is not printed. It only points out to very high level observer widget.

**Comment by neokree** [comment]
@pavanpodila This does not resolve the issue, please reopen it.

Stacktraces are now tracked, but are not displayed in the console. 
Debugging I noticed that the library thown multiple exception in the console (one for each `Exception caught by flutter_mobx` message. 

The useful stacktrace message is in the first one, from the second the stacktrace is from the Observer point of view. I think that every MobXException should paste the entire stacktrace on console, like this:

```
════════ Exception caught by flutter_mobx ══════════════════════════════════════════════════════════
The following MobXCaughtException was thrown:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")

#0      new DeviceMeasurement.fromJson (package:xfarm/src/core/component/main/application/model.dart:1191:10)
#1      ApiHttpClient.getDeviceMeasurements.<anonymous closure> (package:xfarm/src/infrastructure/api/http_client/http_client.dart:563:74)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#4      ApiHttpClient.getDeviceMeasurements (package:xfarm/src/infrastructure/api/http_client/http_client.dart:563:90)
<asynchronous suspension>
#5      _MainStore.fetchDevices (package:xfarm/src/core/component/main/application/observable.dart:334:38)
<asynchronous suspension>
#6      _$MainStore.fetchDevices.<anonymous closure> (package:xfarm/src/core/component/main/application/observable.g.dart:581:54)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _ZoneDelegate.run (dart:async/zone.dart:713:19)
#9      AsyncAction._run (package:mobx/src/api/async/async_action.dart:44:29)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     AsyncAction.run (package:mobx/src/api/async/async_action.dart:29:26)
#12     _$MainStore.fetchDevices (package:xfarm/src/core/component/main/application/observable.g.dart:581:38)
#13     _SplashScreenState.loadDataFromServer (package:xfarm/src/ui/core/component/splash_screen/widget.dart:99:21)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#30     AsyncAction.run (package:mobx/src/api/async/async_action.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#37     Future._complete (dart:async/future_impl.dart:514:7)
#38     new Future.microtask.<anonymous closure> (dart:async/future.dart:202:16)
#39     _rootRun (dart:async/zone.dart:1122:38)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#43     _rootRun (dart:async/zone.dart:1126:13)
#44     _CustomZone.run (dart:async/zone.dart:1023:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)


════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
MobXCaughtException: NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(".")
The relevant error-causing widget was: 
  Observer file:///Users/neokree/Documents/Flutter/project/lib/src/ui/core/component/map/widget.dart:342:18

#0      new DeviceMeasurement.fromJson (package:xfarm/src/core/component/main/application/model.dart:1191:10)
#1      ApiHttpClient.getDeviceMeasurements.<anonymous closure> (package:xfarm/src/infrastructure/api/http_client/http_client.dart:563:74)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#4      ApiHttpClient.getDeviceMeasurements (package:xfarm/src/infrastructure/api/http_client/http_client.dart:563:90)
<asynchronous suspension>
#5      _MainStore.fetchDevices (package:xfarm/src/core/component/main/application/observable.dart:334:38)
<asynchronous suspension>
#6      _$MainStore.fetchDevices.<anonymous closure> (package:xfarm/src/core/component/main/application/observable.g.dart:581:54)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _ZoneDelegate.run (dart:async/zone.dart:713:19)
#9      AsyncAction._run (package:mobx/src/api/async/async_action.dart:44:29)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     AsyncAction.run (package:mobx/src/api/async/async_action.dart:29:26)
#12     _$MainStore.fetchDevices (package:xfarm/src/core/component/main/application/observable.g.dart:581:38)
#13     _SplashScreenState.loadDataFromServer (package:xfarm/src/ui/core/component/splash_screen/widget.dart:99:21)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#30     AsyncAction.run (package:mobx/src/api/async/async_action.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#37     Future._complete (dart:async/future_impl.dart:514:7)
#38     new Future.microtask.<anonymous closure> (dart:async/future.dart:202:16)
#39     _rootRun (dart:async/zone.dart:1122:38)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#43     _rootRun (dart:async/zone.dart:1126:13)
#44     _CustomZone.run (dart:async/zone.dart:1023:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Sure this is a lot verbose, but at least it would allow us to know the real source of the exception.

**Comment by neokree** [comment]
ok now using the same version a stacktrace is tracked for the first Exception as requested. 

At this point I don't know why, but it seems that the stacktrace is not always fetched correctly. 
Sometimes the stacktrace is shown, sometimes is not.

**Comment by pavanpodila** [comment]
I think there might be some truncation on the console. @rrousselGit any idea ?

**Comment by deadsoul44** [comment]
When stack trace is truncated, I use the debug print as following. It might help.

```
catch (e, s) {
      debugPrint('e: ' + e.toString(), wrapWidth: 1000);
      debugPrint('s: ' + s.toString(), wrapWidth: 1000);
    }
```

**Comment by neokree** [comment]
Ok now I can see the trucated stacktrace, don't know why they did not show up previously. 

However the stacktrace for the first `MobXException` is always the one from the widget point of view, not the `Store` point of view. 

This means that we know which `Observer` crashed, but not line in the `Observable` or `Computed` that made them crash.

**Comment by pavanpodila** [comment]
This an area I have to explore, as to how to make the complete stack trace visible without any truncation.

**Comment by hramnathnayak** [comment]
Can you check if the flutter Dev tools logging view shows the complete trace? I have seen the log truncation on vscode console too but was able to see complete trace on the flutter Dev tools.
