### ISSUE TITLE
Computed doesn't update when no observer is used

### ISSUE THREAD

**Issue by ganeshrvel** [mobxjs/mobx.dart#629]
I am trying to build an application which relies heavily on computed values. But AFAIK, the computed values doesn't get updated unless an observer is watching the variable. There are a lot times when I wanted the computed values to be updated in the background but unfortunately they require an observer.

I know that we could use actions to set the variables manually but that is too much of overhead and beats the purpose of computed function.

Are there any work around for this?

**Comment by giri-jeedigunta** [comment]
By definition the computed values have to be derived out of the observable

**Comment by giri-jeedigunta** [comment]
Here is an example ... in the below code left and right are observables... total is computed and is a result of left + right ![image](https://user-images.githubusercontent.com/2689410/107903059-3f0f8700-6f6e-11eb-91fb-8623efc9c73b.jpeg)

**Comment by ganeshrvel** [comment]
I understand that code but unfortunately the computed function doesn't update unless there was an observer in the first place. How do i use a computed function when there is no observer mounted in that particular screen?

**Comment by Rudiksz** [comment]
That doesn't sound right. How do you know it doesn't update if you are not observing it?
Do you have an example code that reproduces the error?

**Comment by ganeshrvel** [comment]
> That doesn't sound right. How do you know it doesn't update if you are not observing it?

Using computed methods inside event handler methods like onTap, onLongPress events. I have noticed the same issue in multiple other projects i have worked on.

**Comment by Rudiksz** [comment]
Store:

```Dart
import 'package:mobx/mobx.dart';

part 'test.g.dart';

class TestStore = _TestStore with _$TestStore;

abstract class _TestStore with Store {
  @observable
  int left = 0;

  @observable
  int right = 0;

  @computed
  int get total => left + right;
}
```

App:
```Dart
void main() async {
  final counter = TestStore();

  runApp(
    MaterialApp(
      home: Material(
        child: Column(
          children: [
            Text('Left:'),
            TextField(
              onChanged: (value) => counter.left = int.tryParse(value) ?? 0,
            ),
            Divider(),
            Text('Right:'),
            TextField(
              onChanged: (value) => counter.right = int.tryParse(value) ?? 0,
            ),
            Divider(),
            ElevatedButton(
              onPressed: () => print(counter.total),
              child: Text('Print total'),
            )
          ],
        ),
      ),
    ),
  );
}
```

There's not a single Observer in the whole app, and the computed works as expected. Your issue is not with computeds, but someplace else. If you don't have code that we can look at it's very hard to help you.

**Comment by ganeshrvel** [comment]
The above code still requires the computed variable to be referred somewhere inside the flutter widget to update itself.

Modifying the above code as:
```dart
import 'package:flutter/material.dart';
import 'package:mobx/mobx.dart';

part 'test_screen.g.dart';

class TestStore = _TestStore with _$TestStore;

abstract class _TestStore with Store {
  @observable
  int left = 0;

  @observable
  int right = 0;

  @computed
  int get total {
    final t = left + right;

    print('Total using computed: ${total}');

    return t;
  }

  ReactionDisposer get autorunDispose => autorun(
        (_) {
          print('Total using autorunDispose: ${total}');
        },
      );

  ReactionDisposer get whenDispose =>
      when((_) => total > 0, () => print('Total using when: ${total}'));

  List<ReactionDisposer> get reactionDisposer => [
        reaction(
          (_) => total,
          (int t) {
            print('Total using reactionDisposer: ${t}');
          },
        ),
      ];
}

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  late final TestStore counter = TestStore();

  @override
  void dispose() {
    super.dispose();

    counter.autorunDispose();
    counter.whenDispose();

    counter.reactionDisposer.forEach((disposer) {
      disposer();
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Column(
          children: [
            Text('Left:'),
            TextField(
              onChanged: (value) => counter.left = int.tryParse(value) ?? 0,
            ),
            Divider(),
            Text('Right:'),
            TextField(
              onChanged: (value) => counter.right = int.tryParse(value) ?? 0,
            ),
            Divider(),
          ],
        ),
      ),
    );
  }
}

```

There are 4 `print` statements in the mobx and none of them prints anything as I havent used the `counter.total` anywhere inside the widget tree. 
Is this because `@computed` observable in mobx requires a flutter interface to activate?

Regards.

**Comment by Rudiksz** [comment]
You set up your reactions and dispose of them immediately, your problem has nothing to do with computeds or flutter.

```counter.autorunDispose();```
The autorunDispose is a getter, so "counter.autodispose" actually runs your autorun function which returns the disposer. Adding () at the end will run the disposer. The problem is that you did not set up the disposer before. Getters are just functions and are executed only if called. Which leads to another problem, accessing the disposer more than once will set up new reactions every time.

The proper way to do this is:

```Dart
abstract class _TestStore with Store {
  late ReactionDisposer autorunDispose;
  late ReactionDisposer whenDispose;
  late List<ReactionDisposer> reactionDisposer;

  _TestStore(){
     autorunDispose = autorun(
        (_) {
          print('Total using autorunDispose: ${total}');
        },
      );

  whenDispose =
      when((_) => total > 0, () => print('Total using when: ${total}'));

  reactionDisposer = [
        reaction(
          (_) => total,
          (int t) {
            print('Total using reactionDisposer: ${t}');
          },
        ),
      ];
  }

  @observable
  int left = 0;

  @observable
  int right = 0;

  @computed
  int get total {
    final t = left + right;

    print('Total using computed: ${total}');

    return t;
  }
}```

**Comment by ganeshrvel** [comment]
The above code throws an error:

```
flutter: │ MobXCaughtException: Cycle detected in computation _TestStore.total: Closure: () => int

flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   Computed.value (package:mobx/src/core/computed.dart:91:7)
flutter: │ #1   _$TestStore.total (package:my_app/test_screen.g.dart:17:8)
flutter: │ #2   new _TestStore.<anonymous closure> (package:my_app/test_screen.dart:110:16)
flutter: │ #3   createReaction.reactionRunner.<anonymous closure> (package:mobx/src/core/reaction_helper.dart:94:27)
flutter: │ #4   ReactiveContext.trackDerivation (package:mobx/src/core/context.dart:250:20)
flutter: │ #5   ReactionImpl.track (package:mobx/src/core/reaction.dart:84:14)
flutter: │ #6   createReaction.reactionRunner (package:mobx/src/core/reaction_helper.dart:93:9)
flutter: │ #7   createReaction.<anonymous closure> (package:mobx/src/core/reaction_helper.dart:120:7)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
```


How do we fix this?

**Comment by Rudiksz** [comment]
remove the print statement from the computed
