### ISSUE TITLE
Error when running mobx_codegen

### ISSUE THREAD

**Issue by rogsilva** [mobxjs/mobx.dart#659]
Hi,
The below error occurred after I upgrade the flutter to use the null-safety version.

```bash
[SEVERE] mobx_codegen:mobx_generator on test/common/repositories/oauth_repository_test.dart:

Null check operator used on a null value
#0      LinkedElementFactory.isLibraryUri (package:analyzer/src/summary2/linked_element_factory.dart:418:48)
#1      LibraryContext.isLibraryUri (package:analyzer/src/dart/analysis/library_context.dart:96:27)
#2      LibraryAnalyzer._isLibrarySource (package:analyzer/src/dart/analysis/library_analyzer.dart:521:25)
#3      LibraryAnalyzer._resolveDirectives (package:analyzer/src/dart/analysis/library_analyzer.dart:562:36)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:127:5)
#5      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:104:12)
#6      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1315:63)
#7      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#8      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#9      AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1369:26)
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:987:20)
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2006:24)
<asynchronous suspension>

package:analyzer/src/dart/analysis/driver.dart 1344:9             AnalysisDriver._computeAnalysisResult.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 32:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1286:20            AnalysisDriver._computeAnalysisResult
package:analyzer/src/dart/analysis/driver.dart 1369:26            AnalysisDriver._computeErrors
package:analyzer/src/dart/analysis/driver.dart 987:20             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2006:24            AnalysisDriverScheduler._run
```

**Flutter version**
```
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (2 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

**Packages versions**
```yaml
dependencies:
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

dev_dependencies:
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.12.2
```
Do you have any idea what could cause this error?

**Comment by rogsilva** [comment]
I upgraded the `build_runner` to version `2.0.1` and the `analyzer` to version `1.5.0`, but the problem remains.

**Comment by jfelipe72** [comment]
Your fix worked for me 🚀

**Comment by rogsilva** [comment]
Closing because it is a bug of the analyzer package
https://github.com/dart-lang/sdk/pull/45823
