### ISSUE TITLE
Avoid `setState() or markNeedsBuild() called during build` by automatically wait for a frame whenever needed

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#768]
## Description

During development, I often see the `setState() or markNeedsBuild() called during build` error. Of course, I can avoid it by inserting `addPostFrameCallback` here and there, but some bugs happen under quite strange conditions so it is not easy to do so. In addition, mobx is known to be highly automatic (compared with, e.g. redux), so it is good to hide such details and automatically do the right thing ("wait for a frame").

## Proposed solution

By using https://stackoverflow.com/questions/71367080/automatically-determine-whether-to-wait-for-a-frame-to-avoid-setstate-or-mark or https://stackoverflow.com/a/64702218/4619958, we may do the following: 

* Whenever possible, it calls setState directly. Thus, we do not have a one-frame latency.
* If not possible (i.e. direct setState will lead to the error above), it waits for a frame and setState then. If needed, we can warn or log to tell the user this happens.

## Reproducible sample (mobx generated code included)

Here is a minimal reproducible sample that is simplified from a real-world example in my app in production.

Steps:

* open app
* click the button
* see error

Logs:

```shell
Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
Restarted application in 397ms.
flutter: One.build
flutter: One.Observer.build
flutter: One.build
flutter: One.Observer.build
flutter: TwoChild.initState
flutter: Store.fetch set to pending
flutter: TwoChild.build
flutter: TwoChild.Observer.build

======== Exception caught by flutter_mobx ==========================================================
The following MobXCaughtException was thrown From reaction of Observer
#3      One.build (package:yplusplus/main.dart:52:9) of type StatelessObserverElement.:
setState() or markNeedsBuild() called during build.
This Observer widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Observer
The widget which was currently being built when the offending call was made was:
  Observer

When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4424:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4439:6)
#2      ObserverElementMixin.invalidate (package:flutter_mobx/src/observer_widget_mixin.dart:71:24)
#3      ReactionImpl._run (package:mobx/src/core/reaction.dart:117:22)
#4      ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:351:18)
#5      ReactiveContext.runReactions (package:mobx/src/core/context.dart:325:5)
#6      ReactiveContext.endBatch (package:mobx/src/core/context.dart:155:7)
#7      ActionController.endAction (package:mobx/src/core/action.dart:110:9)
#8      AsyncAction._run (package:mobx/src/api/async/async_action.dart:46:16)
#10     AsyncAction.run (package:mobx/src/api/async/async_action.dart:28:26)
#11     _$_MyStore.fetch (package:yplusplus/main.dart:162:32)
#12     _TwoChildState.initState (package:yplusplus/main.dart:93:18)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#28     _invoke (dart:ui/hooks.dart:151:10)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#30     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 4 frames from dart:async)
====================================================================================================
flutter: Store.fetch set to fulfilled
flutter: TwoChild.Observer.build
```

Code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:mobx/mobx.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final store = _MyStore();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            One(store: store),
            Two(store: store),
          ],
        ),
      ),
    );
  }
}

class One extends StatelessWidget {
  final _MyStore store;

  const One({Key? key, required this.store}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print('One.build');
    return Column(
      children: [
        Observer(builder: (_) {
          print('One.Observer.build');
          return Text('One read status: ${store.status}');
        }),
        TextButton(onPressed: () => store.showTwo = true, child: const Text('click me')),
      ],
    );
  }
}

class Two extends StatelessWidget {
  final _MyStore store;

  const Two({Key? key, required this.store}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Observer(builder: (_) {
      if (store.showTwo) {
        return TwoChild(store: store);
      } else {
        return const Text('Two: empty');
      }
    });
  }
}

class TwoChild extends StatefulWidget {
  final _MyStore store;

  const TwoChild({Key? key, required this.store}) : super(key: key);

  @override
  _TwoChildState createState() => _TwoChildState();
}

class _TwoChildState extends State<TwoChild> {
  @override
  void initState() {
    super.initState();
    print('TwoChild.initState');
    widget.store.fetch();
  }

  @override
  Widget build(BuildContext context) {
    print('TwoChild.build');
    return Observer(builder: (_) {
      print('TwoChild.Observer.build');
      return Text('TwoChild read status: ${widget.store.status}');
    });
  }
}

class _MyStore = __MyStore with _$_MyStore;

abstract class __MyStore with Store {
  @observable
  var showTwo = false;

  @observable
  FutureStatus? status;

  @action
  Future<void> fetch() async {
    print('Store.fetch set to pending');
    status = FutureStatus.pending;

    await Future<void>.delayed(const Duration(seconds: 1));

    print('Store.fetch set to fulfilled');
    status = FutureStatus.fulfilled;
  }
}

mixin _$_MyStore on __MyStore, Store {
  final _$_showTwoAtom = Atom(name: '__MyStore.showTwo');

  @override
  bool get showTwo {
    _$_showTwoAtom.reportRead();
    return super.showTwo;
  }

  @override
  set showTwo(bool value) {
    _$_showTwoAtom.reportWrite(value, super.showTwo, () {
      super.showTwo = value;
    });
  }

  final _$_statusAtom = Atom(name: '__MyStore.status');

  @override
  FutureStatus? get status {
    _$_statusAtom.reportRead();
    return super.status;
  }

  @override
  set status(FutureStatus? value) {
    _$_statusAtom.reportWrite(value, super.status, () {
      super.status = value;
    });
  }

  final _$_fetchAsyncAction = AsyncAction('__BaseHttpAction.fetch');

  @override
  Future<void> fetch() {
    return _$_fetchAsyncAction.run(() => super.fetch());
  }

  @override
  String toString() {
    return '''

    ''';
  }
}
```

**Comment by fzyzcjy** [comment]
@pavanpodila What do you think about it? If the `proposed solution` mentioned above sounds OK I will try to implement it.

**Comment by fzyzcjy** [comment]
Anyway I will work on it

**Comment by fzyzcjy** [comment]
@pavanpodila Btw I have no permission to push to `master`, so I push to my fork and pr it

**Comment by pavanpodila** [comment]
Yes. That's by design
