### ISSUE TITLE
mobx_codegen throws RangeError when Dart 2.17 enums are used somewhere in code

### ISSUE THREAD

**Issue by scrinoman** [mobxjs/mobx.dart#827]
I just tried to add "enhanced" enums presented with dart 2.17 to my project.

``` dart
enum _Priority {
  low(0),
  normal(1),
  top(2);

  const _NavigationPriority(this.value);

  factory _NavigationPriority.forRouteName(String? name) {
    ...
  }

  final int value;
}
```

Running `flutter pub run build_runner build --delete-conflicting-outputs` gives the following error and stack:

```
[SEVERE] mobx_codegen:mobx_generator on <just random file from my project, different one every run>:

RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      ElementWalker.getConstructor (package:analyzer/src/generated/declaration_resolver.dart:159:21)
#2      ResolutionVisitor.visitConstructorDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:283:54)
#3      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2512:15)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#5      ResolutionVisitor.visitEnumDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:415:22)
#6      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1413:8)
#7      ResolutionVisitor.visitEnumDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:408:7)
#8      ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1402:8)
#9      ResolutionVisitor.visitEnumDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:407:5)
#10     EnumDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3405:50)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2105:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:765:10)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#15     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:752:10)
#16     LibraryAnalyzer._parseAndResolve.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:597:7)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#18     LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:596:11)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:105:17)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1447:11)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1424:20)
#23     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1485:26)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1097:20)
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2127:24)
<asynchronous suspension>

```

If I switch back to classic enum, everything runs smoothly.

Tried to find out the exact "enhanced" feature, that causes gen error:
1) removed `value` and const constructor, but keep `factory` one;
2) removed `factory` constructor, but keep everything else.

In both cases error still occurred.

`flutter doctor -v` output:
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale ru-RU)
    • Flutter version 3.0.1 at /Users/nikitaivanov/development/fvm/versions/3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nikitaivanov/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • MI 5s (mobile)  • 8ce82552 • android-arm64  • Android 9 (API 28)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by Alba-22** [comment]
I'm getting this exact same error when trying to use enhanced enums with mobx

**Comment by scrinoman** [comment]
Yep, it worked. Closing this issue since it's related to dart-lang

**Comment by scrinoman** [comment]
Yep, it worked. Closing this issue since it's related to dart-lang
